import React, { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Clock3, Search, UserMinus, UserPlus, Users, X } from "lucide-react";
import { Link } from "react-router-dom";
import { appClient } from "@/api/appClient";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/components/ui/use-toast";

const presence = { online: "bg-emerald-400", idle: "bg-yellow-400", dnd: "bg-red-500", invisible: "bg-slate-500" };
function Avatar({ player }) { return <div className="relative h-11 w-11 shrink-0 overflow-hidden rounded-full bg-secondary">{player.avatar_url ? <img src={player.avatar_url} alt="" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center font-bold">{player.display_name?.[0]?.toUpperCase()}</div>}<span className={`absolute bottom-0 right-0 h-3.5 w-3.5 rounded-full border-2 border-card ${presence[player.presence_style] || "bg-slate-500"}`} /></div>; }

export default function FriendsPanel() {
  const queryClient = useQueryClient(); const { toast } = useToast();
  const [tab, setTab] = useState("friends"); const [search, setSearch] = useState(""); const [results, setResults] = useState([]);
  const { data: stateResponse, isLoading } = useQuery({ queryKey: ["friends_state"], queryFn: () => appClient.functions.invoke("getFriendsState"), refetchInterval: 30_000 });
  const state = stateResponse?.data || { friends: [], incoming: [], outgoing: [] };
  const refresh = () => Promise.all([queryClient.invalidateQueries({ queryKey: ["friends_state"] }), queryClient.invalidateQueries({ queryKey: ["public_profile"] })]);
  const searchMutation = useMutation({ mutationFn: query => appClient.functions.invoke("searchFriendPlayers", { query }), onSuccess: response => setResults(response.data), onError: error => toast({ title: "Recherche impossible", description: error.message, variant: "destructive" }) });
  const send = useMutation({ mutationFn: userId => appClient.functions.invoke("sendFriendRequest", { user_id: userId }), onSuccess: () => { refresh(); setResults([]); toast({ title: "Demande envoyée" }); }, onError: error => toast({ title: "Demande impossible", description: error.message, variant: "destructive" }) });
  const manage = useMutation({ mutationFn: payload => appClient.functions.invoke("manageFriendship", payload), onSuccess: (_, payload) => { refresh(); toast({ title: payload.action === "accept" ? "Nouvel ami ajouté" : "Liste d’amis mise à jour" }); }, onError: error => toast({ title: "Action impossible", description: error.message, variant: "destructive" }) });
  const doSearch = event => { event.preventDefault(); if (search.trim().length >= 2) searchMutation.mutate(search.trim()); };
  const PlayerRow = ({ player, actions }) => <div className="flex items-center gap-3 rounded-xl border border-border/60 bg-secondary/20 p-3"><Avatar player={player} /><div className="min-w-0 flex-1"><Link to={`/profile/${player.user_id}`} className="truncate text-sm font-bold hover:text-primary hover:underline">{player.display_name}</Link><p className="truncate text-[10px] text-muted-foreground">Niveau {player.player_level || 1}{player.status_text ? ` · ${player.status_emoji || ""} ${player.status_text}` : ""}</p></div><div className="flex shrink-0 gap-1">{actions}</div></div>;
  return <section className="rounded-2xl border border-border bg-card p-4 sm:p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 font-display text-lg font-bold"><Users className="h-5 w-5 text-primary" />Amis</h2><p className="text-xs text-muted-foreground">{state.friends.length} ami{state.friends.length !== 1 ? "s" : ""}{state.incoming.length ? ` · ${state.incoming.length} demande${state.incoming.length > 1 ? "s" : ""}` : ""}</p></div><div className="flex gap-1 rounded-xl bg-secondary/40 p-1">{[["friends","Mes amis"],["requests",`Demandes${state.incoming.length ? ` (${state.incoming.length})` : ""}`],["add","Ajouter"]].map(([id,label]) => <button key={id} onClick={() => setTab(id)} className={`rounded-lg px-3 py-1.5 text-[10px] font-bold ${tab === id ? "bg-primary text-white" : "text-muted-foreground"}`}>{label}</button>)}</div></div>
    {tab === "friends" && <div className="grid gap-2 sm:grid-cols-2">{state.friends.map(player => <PlayerRow key={player.id} player={player} actions={<Button size="icon" variant="ghost" aria-label={`Retirer ${player.display_name}`} onClick={() => manage.mutate({ friendship_id: player.id, action: "remove" })}><UserMinus className="h-4 w-4" /></Button>} />)}{!isLoading && !state.friends.length && <div className="col-span-full rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">Ta liste est vide. Recherche un joueur pour commencer.</div>}</div>}
    {tab === "requests" && <div className="space-y-4"><div><p className="mb-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Demandes reçues</p><div className="grid gap-2 sm:grid-cols-2">{state.incoming.map(player => <PlayerRow key={player.id} player={player} actions={<><Button size="icon" aria-label={`Accepter ${player.display_name}`} onClick={() => manage.mutate({ friendship_id: player.id, action: "accept" })}><Check className="h-4 w-4" /></Button><Button size="icon" variant="outline" aria-label={`Refuser ${player.display_name}`} onClick={() => manage.mutate({ friendship_id: player.id, action: "decline" })}><X className="h-4 w-4" /></Button></>} />)}{!state.incoming.length && <p className="text-xs text-muted-foreground">Aucune demande reçue.</p>}</div></div><div><p className="mb-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Demandes envoyées</p><div className="grid gap-2 sm:grid-cols-2">{state.outgoing.map(player => <PlayerRow key={player.id} player={player} actions={<Button size="icon" variant="outline" aria-label={`Annuler la demande à ${player.display_name}`} onClick={() => manage.mutate({ friendship_id: player.id, action: "cancel" })}><X className="h-4 w-4" /></Button>} />)}{!state.outgoing.length && <p className="text-xs text-muted-foreground">Aucune demande en attente.</p>}</div></div></div>}
    {tab === "add" && <div><form onSubmit={doSearch} className="flex gap-2"><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="Rechercher un pseudo…" maxLength={24} /><Button type="submit" disabled={search.trim().length < 2 || searchMutation.isPending}><Search className="mr-2 h-4 w-4" />Rechercher</Button></form><div className="mt-3 grid gap-2 sm:grid-cols-2">{results.map(player => <PlayerRow key={player.user_id} player={player} actions={player.relation_status === "none" ? <Button size="sm" onClick={() => send.mutate(player.user_id)}><UserPlus className="mr-1 h-4 w-4" />Ajouter</Button> : player.relation_status === "incoming" ? <Button size="sm" onClick={() => manage.mutate({ friendship_id: player.friendship_id, action: "accept" })}><Check className="mr-1 h-4 w-4" />Accepter</Button> : <span className="flex items-center gap-1 text-[10px] text-muted-foreground"><Clock3 className="h-3 w-3" />{player.relation_status === "friend" ? "Déjà ami" : "En attente"}</span>} />)}</div></div>}
  </section>;
}
