import React, { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArchiveRestore, Check, Clock, DatabaseBackup, Eye, Flag, ShieldAlert, VolumeX, X } from "lucide-react";
import { appClient } from "@/api/appClient";
import { Button } from "@/components/ui/button";
import { useToast } from "@/components/ui/use-toast";

const dateLabel = value => value ? new Date(value).toLocaleString("fr-FR") : "—";
const sizeLabel = value => `${Math.max(0, Number(value || 0)) < 1024 * 1024 ? (Number(value || 0) / 1024).toFixed(1) + " Ko" : (Number(value || 0) / 1024 / 1024).toFixed(1) + " Mo"}`;

export default function AdminSecurityCenter() {
  const [section, setSection] = useState("risks");
  const [selectedPlayer, setSelectedPlayer] = useState(null);
  const queryClient = useQueryClient();
  const { toast } = useToast();

  const { data: overviewResponse, isLoading: overviewLoading } = useQuery({ queryKey: ["admin_security"], queryFn: () => appClient.functions.invoke("getAdminSecurityOverview"), refetchInterval: 30_000 });
  const { data: backupsResponse, isLoading: backupsLoading } = useQuery({ queryKey: ["admin_backups"], queryFn: () => appClient.functions.invoke("getAdminBackups") });
  const { data: activityResponse, isLoading: activityLoading } = useQuery({ queryKey: ["admin_player_activity", selectedPlayer?.id], queryFn: () => appClient.functions.invoke("getAdminPlayerActivity", { user_id: selectedPlayer.id }), enabled: !!selectedPlayer });
  const overview = overviewResponse?.data || { players: [], pending_reports: [] };
  const backups = backupsResponse?.data || [];
  const activity = activityResponse?.data?.activity || [];

  const refreshSecurity = () => Promise.all([queryClient.invalidateQueries({ queryKey: ["admin_security"] }), queryClient.invalidateQueries({ queryKey: ["admin_audit"] }), queryClient.invalidateQueries({ queryKey: ["admin_users"] })]);
  const createBackup = useMutation({ mutationFn: () => appClient.functions.invoke("createAdminBackup"), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["admin_backups"] }); toast({ title: "Sauvegarde créée", description: "Une copie compressée est maintenant conservée dans MongoDB." }); }, onError: error => toast({ title: "Sauvegarde impossible", description: error.message, variant: "destructive" }) });
  const restoreBackup = useMutation({ mutationFn: backupId => appClient.functions.invoke("restoreAdminBackup", { backup_id: backupId, confirmation: "RESTAURER" }), onSuccess: response => { refreshSecurity(); toast({ title: "Base restaurée", description: `${response.data.users_count} comptes et ${response.data.cards_count} cartes restaurés.` }); }, onError: error => toast({ title: "Restauration impossible", description: error.message, variant: "destructive" }) });
  const moderate = useMutation({ mutationFn: payload => appClient.functions.invoke("adminModerateUser", payload), onSuccess: () => { refreshSecurity(); toast({ title: "Modération appliquée" }); }, onError: error => toast({ title: "Action impossible", description: error.message, variant: "destructive" }) });
  const resolveReport = useMutation({ mutationFn: payload => appClient.functions.invoke("resolveChatReport", payload), onSuccess: refreshSecurity, onError: error => toast({ title: "Action impossible", description: error.message, variant: "destructive" }) });

  const confirmRestore = backup => {
    const confirmation = window.prompt(`Cette action remplacera les données actuelles par la sauvegarde du ${dateLabel(backup.created_at)}.\n\nÉcris RESTAURER pour confirmer.`);
    if (confirmation === "RESTAURER") restoreBackup.mutate(backup.id);
  };

  return (
    <div className="space-y-5">
      <div className="rounded-2xl border border-red-500/20 bg-gradient-to-r from-red-950/30 to-card p-4 sm:p-6"><div className="flex items-center gap-3"><ShieldAlert className="h-8 w-8 text-red-400"/><div><h2 className="font-display text-xl font-bold">Sécurité et modération</h2><p className="text-xs text-muted-foreground">Sauvegardes, signalements et détection des activités inhabituelles.</p></div></div></div>
      <div className="grid grid-cols-3 gap-2">{[["risks", "Risques", ShieldAlert], ["reports", `Signalements (${overview.pending_reports.length})`, Flag], ["backups", "Sauvegardes", DatabaseBackup]].map(([id, label, Icon]) => <Button key={id} variant={section === id ? "default" : "outline"} className="h-auto min-h-11 whitespace-normal px-2 text-xs sm:text-sm" onClick={() => setSection(id)}><Icon className="mr-1.5 h-4 w-4 shrink-0"/>{label}</Button>)}</div>

      {section === "risks" && <div className="space-y-3">
        {overviewLoading && <p className="py-10 text-center text-sm text-muted-foreground">Analyse en cours…</p>}
        {overview.players.map(player => <article key={player.id} className={`rounded-2xl border p-4 ${player.risk === "high" ? "border-red-500/40 bg-red-500/5" : player.risk === "medium" ? "border-orange-500/30 bg-orange-500/5" : "border-border bg-card"}`}><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="truncate">{player.name || player.email}</strong><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${player.risk === "high" ? "bg-red-500/20 text-red-300" : player.risk === "medium" ? "bg-orange-500/20 text-orange-300" : "bg-emerald-500/15 text-emerald-300"}`}>{player.risk === "low" ? "NORMAL" : player.risk === "medium" ? "À VÉRIFIER" : "RISQUE ÉLEVÉ"}</span>{player.chat_muted_until && new Date(player.chat_muted_until) > new Date() && <span className="rounded-full bg-purple-500/15 px-2 py-0.5 text-[10px] text-purple-300">MUET</span>}</div><p className="truncate text-xs text-muted-foreground">{player.email}</p><div className="mt-2 flex flex-wrap gap-3 text-[11px] text-muted-foreground"><span>{player.coins.toLocaleString("fr-FR")} pièces</span><span>{player.cards} cartes</span><span>{player.transactions_24h} transactions/24h</span><span>{player.messages_24h} messages/24h</span></div>{player.flags.length > 0 && <div className="mt-2 flex flex-wrap gap-1">{player.flags.map(flag => <span key={flag} className="rounded bg-red-500/10 px-2 py-1 text-[10px] text-red-300">{flag}</span>)}</div>}</div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => setSelectedPlayer(player)}><Eye className="mr-1.5 h-4 w-4"/>Historique</Button>{player.chat_muted_until && new Date(player.chat_muted_until) > new Date() ? <Button size="sm" variant="outline" onClick={() => moderate.mutate({ user_id: player.id, action: "unmute" })}>Rendre la parole</Button> : <Button size="sm" variant="outline" className="text-purple-300" onClick={() => moderate.mutate({ user_id: player.id, action: "mute", minutes: 60, reason: "Modération administrateur" })}><VolumeX className="mr-1.5 h-4 w-4"/>Mute 1 h</Button>}</div></div></article>)}
      </div>}

      {section === "reports" && <div className="space-y-3">{overview.pending_reports.map(report => <article key={report.id} className="rounded-2xl border border-orange-500/25 bg-orange-500/5 p-4"><div className="flex items-start justify-between gap-3"><div><strong className="text-sm">{report.reported_user_name || "Joueur"}</strong><p className="mt-1 rounded-lg bg-black/20 p-3 text-sm">{report.message_text}</p><p className="mt-2 text-[10px] text-muted-foreground">Signalé le {dateLabel(report.created_date)} · {report.reason}</p></div><Flag className="h-5 w-5 shrink-0 text-orange-400"/></div><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" onClick={() => moderate.mutate({ user_id: report.reported_user_id, action: "mute", minutes: 60, reason: "Message signalé" })}><VolumeX className="mr-1 h-3.5 w-3.5"/>Mute 1 h</Button><Button size="sm" variant="outline" onClick={() => resolveReport.mutate({ report_id: report.id, status: "resolved" })}><Check className="mr-1 h-3.5 w-3.5"/>Traité</Button><Button size="sm" variant="ghost" onClick={() => resolveReport.mutate({ report_id: report.id, status: "dismissed" })}><X className="mr-1 h-3.5 w-3.5"/>Ignorer</Button></div></article>)}{!overview.pending_reports.length && <p className="rounded-2xl border border-dashed border-border py-12 text-center text-sm text-muted-foreground">Aucun signalement en attente.</p>}</div>}

      {section === "backups" && <div className="space-y-4"><div className="flex flex-col gap-3 rounded-2xl border border-border bg-card p-4 sm:flex-row sm:items-center sm:justify-between"><div><strong>Sauvegardes MongoDB automatiques</strong><p className="text-xs text-muted-foreground">Une sauvegarde par jour, les 14 dernières sont conservées.</p></div><Button disabled={createBackup.isPending} onClick={() => createBackup.mutate()}><DatabaseBackup className="mr-2 h-4 w-4"/>{createBackup.isPending ? "Création…" : "Sauvegarder maintenant"}</Button></div>{backupsLoading ? <p className="py-10 text-center text-sm text-muted-foreground">Chargement…</p> : backups.map(backup => <article key={backup.id} className="flex flex-col gap-3 rounded-xl border border-border bg-card/70 p-4 sm:flex-row sm:items-center sm:justify-between"><div><strong className="text-sm">{backup.reason === "automatic" ? "Automatique" : backup.reason === "before_restore" ? "Avant restauration" : "Manuelle"}</strong><p className="text-xs text-muted-foreground">{dateLabel(backup.created_at)} · {backup.users_count} comptes · {backup.cards_count} cartes · {sizeLabel(backup.bytes)}</p></div><Button size="sm" variant="outline" disabled={restoreBackup.isPending} onClick={() => confirmRestore(backup)}><ArchiveRestore className="mr-1.5 h-4 w-4"/>Restaurer</Button></article>)}</div>}

      {selectedPlayer && <div className="fixed inset-0 z-[100] grid place-items-center bg-black/80 p-3" onClick={() => setSelectedPlayer(null)}><div className="max-h-[90dvh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-border bg-card p-4 sm:p-6" onClick={event => event.stopPropagation()}><div className="flex items-start justify-between gap-3"><div><h3 className="font-display text-lg font-bold">Historique de {selectedPlayer.name || selectedPlayer.email}</h3><p className="text-xs text-muted-foreground">200 dernières actions enregistrées</p></div><Button size="icon" variant="ghost" onClick={() => setSelectedPlayer(null)}><X className="h-4 w-4"/></Button></div><div className="mt-4 space-y-2">{activityLoading ? <p className="py-8 text-center text-sm text-muted-foreground">Chargement…</p> : activity.map(item => <div key={`${item.type}-${item.id}`} className="flex items-start gap-3 rounded-xl border border-border/60 bg-secondary/20 p-3"><Clock className="mt-0.5 h-4 w-4 shrink-0 text-primary"/><div className="min-w-0 flex-1"><p className="break-words text-sm">{item.label}</p><p className="text-[10px] uppercase text-muted-foreground">{item.type} · {dateLabel(item.created_date)}</p></div>{item.amount !== undefined && <span className="shrink-0 text-xs font-bold">{Number(item.amount).toLocaleString("fr-FR")}</span>}</div>)}{!activityLoading && !activity.length && <p className="py-8 text-center text-sm text-muted-foreground">Aucune activité enregistrée.</p>}</div></div></div>}
    </div>
  );
}
